- hosts: 'tag_Name_HADOOP_CLIENT'
  vars:
    namenode_ip:  ''
    namenode_svc_port: 9001
    jobtracker_ip: ''
    jobtracker_svc_port: '9002'
  tasks:
  - name: Copy the config files 
    template:
      src: "../templates/{{ item }}"
      dest: "/etc/hadoop/{{ item }}"
    loop:
    - core-site.xml
    - mapred-site.xml




