- hosts: 'tag_Name_HADOOP_CLIENT'
  vars:
    namenode_ip: "{{ groups['tag_Name_HADOOP_NAMENODE'][0] }}"
    namenode_svc_port: 9001
    jobtracker_ip: "{{ groups['tag_Name_HADOOP_JOB_TRACKER'][0] }}"
    jobtracker_svc_port: '9002'
  tasks:
  - name: Copy the config files 
    template:
      src: "../templates/{{ item }}"
      dest: "/etc/hadoop/{{ item }}"
    loop:
    - core-site.xml
    - mapred-site.xml

  - name: create dir for hive 
    file:
      path: /opt/apache-hive1/
      state: directory
      recurse: true

  - name: Install and cofigure hive 
    unarchive:
      src: "../files/apache-hive-1.2.2-bin.tar.gz"
      dest: /opt/apache-hive/


  - name: Updating the .bashrc for environmental variables 
    lineinfile:
      line: |
            export HIVE_HOME=/opt/apache-hive/apache-hive-1.2.2-bin/
            export PATH=$PATH:$HIVE_HOME/bin 
      path: /root/.bashrc 
      state: present

  - name: Setting the permission of the tmp folder in hdfs for hive 
    command: 'hadoop fs -chmod 777 /tmp/hive' 
        

